#!/usr/bin/env python3
"""Generate res/xml/drawable.xml from the drawables on disk.

drawable.xml is what populates a launcher's manual icon picker. Everything in
the pack belongs here, including the pieces appfilter.xml does not map, so users
can assign them to whatever they like.

Usage: tools/gen_drawable_xml.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DRAWABLES = ROOT / "app/src/main/res/drawable-nodpi"
OUT = ROOT / "app/src/main/res/xml/drawable.xml"

# Launcher furniture from the original GO/ADW theme: app-drawer buttons, folder
# art, drag targets. No modern launcher consumes these automatically, but they
# are perfectly good icons to hand-assign.
LAUNCHER_ART = {
    "allapp",
    "ap_icon",
    "ap_icon_on",
    "appfunchome",
    "d_del",
    "folder_close_up",
    "folder_open",
    "icon",
}

EXCLUDE = {"ic_launcher_foreground"}


def main() -> None:
    names = sorted(p.stem for p in DRAWABLES.glob("*.png") if p.stem not in EXCLUDE)
    apps = [n for n in names if n not in LAUNCHER_ART]
    art = [n for n in names if n in LAUNCHER_ART]

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by tools/gen_drawable_xml.py — do not edit by hand. -->",
        "<resources>",
        "    <version>1</version>",
    ]
    for title, group in (("Apps", apps), ("Launcher", art)):
        if not group:
            continue
        lines.append(f'    <category title="{title}" />')
        lines.extend(f'    <item drawable="{name}" />' for name in group)
    lines.append("</resources>")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(names)} entries to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
